# Generated by Django 2.1.4 on 2019-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoInfo',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sunrise', models.DateTimeField(auto_now_add=True)),
                ('sunset', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField()),
                ('weather_id', models.IntegerField()),
                ('weather_main', models.CharField(max_length=32)),
                ('weather_description', models.TextField()),
                ('weather_icon', models.CharField(max_length=12)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sea_level', models.IntegerField()),
                ('grnd_level', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_deg', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('rain_1h', models.IntegerField()),
                ('rain_3h', models.IntegerField()),
                ('snow_1h', models.IntegerField()),
                ('snow_3h', models.IntegerField()),
            ],
            options={
                'verbose_name': 'meteo',
                'verbose_name_plural': 'meteo',
                'ordering': ['-update_time'],
            },
        ),
    ]
